/** @type {import("../helpers/errors.js").ErrorMap} */
export const ERROR_TYPES = {
  NOT_FOUND: { CODE: "NOT_FOUND", STATUS_CODE: 404 },
  BAD_REQUEST: { CODE: "BAD_REQUEST", STATUS_CODE: 400 },
  UNAUTHORIZED: { CODE: "UNAUTHORIZED", STATUS_CODE: 401 },
  FORBIDDEN: { CODE: "FORBIDDEN", STATUS_CODE: 403 },
  METHOD_NOT_ALLOWED: { CODE: "METHOD_NOT_ALLOWED", STATUS_CODE: 405 },
  CONFLICT: { CODE: "CONFLICT", STATUS_CODE: 409 },
  INTERNAL_SERVER_ERROR: { CODE: "INTERNAL_SERVER_ERROR", STATUS_CODE: 500 },
};

export const ERR_MESSAGE = {
  UNIQUE: {
    USER_PHONE_NUMBER_UNIQUE: {
      NAME: "USER_PHONE_NUMBER_UNIQUE",
      MESSAGE: "Phone Number Is Already Taken",
    },
    USER_EMAIL_UNIQUE: {
      NAME: "USER_EMAIL_UNIQUE",
      MESSAGE: "Email is Already Taken",
    },
  },
  AUTH: {
    INVALID_CREDENTIALS: "Email /Password Mismatch",
  },
};
